In [2]:
import numpy as np
import time
import sys

i = range(1000)
print(sys.getsizeof(5)*len(i))

array = np.arange(1000)
print(array.size*array.itemsize)

28000
4000


In [5]:
#2
SIZE = 1000000

l1 = range(SIZE)
l2 = range(SIZE)

a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

#python list
start = time.time()
result = [(x+y) for x, y in zip(l1, l2)]
print("python list took: ", (time.time()-start)*1000)

#numpy array
start = time.time()
result = a1 + a2
print("numpy took: ", (time.time()-start) *1000)

python list took:  275.285005569458
numpy took:  25.034427642822266


In [9]:
#mupy basic array operations
import numpy

a = np.array([2, 6, 7])
a[0]


2

In [10]:
b = np.array([[1, 2], [3, 4], [5, 6]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
b.ndim

1

In [13]:
a.ndim

1

In [14]:
b.itemsize

4

In [15]:
b.dtype

dtype('int32')

In [17]:
b = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.float64)
b

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [19]:
b.itemsize

8

In [20]:
b.size

6

In [21]:
b.shape

(3, 2)

In [22]:
b = np.array([[1, 2], [3, 4], [5, 6]], dtype=complex)
b

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [24]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
l = range(5)
l

range(0, 5)

In [27]:
l[0]

0

In [28]:
np.arange(1,5)

array([1, 2, 3, 4])

In [30]:
np.arange(1,5,2)

array([1, 3])

In [31]:
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [33]:
b = np.array([[1, 2], [3, 4], [5, 6]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
b.shape

(3, 2)

In [37]:
b.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
b.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [40]:
b.ravel() #do not change the original array

array([1, 2, 3, 4, 5, 6])

In [41]:
b.min()

1

In [42]:
b.max()

6

In [43]:
b.sum()

21

In [44]:
b.sum(axis=0)

array([ 9, 12])

In [45]:
b.sum(axis=1)

array([ 3,  7, 11])

In [47]:
np.sqrt(a)

array([1.41421356, 2.44948974, 2.64575131])

In [48]:
np.std(b)

1.707825127659933

In [49]:
c = np.array([[1,2], [3,4]])
d = np.array([[5,6], [7,8]])


In [50]:
c

array([[1, 2],
       [3, 4]])

In [51]:
d

array([[5, 6],
       [7, 8]])

In [52]:
c+d

array([[ 6,  8],
       [10, 12]])

In [53]:
c-d

array([[-4, -4],
       [-4, -4]])

In [54]:
c*d

array([[ 5, 12],
       [21, 32]])

In [55]:
c/d

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [56]:
c.dot(d)

array([[19, 22],
       [43, 50]])

In [57]:
#numpy: slicing/stacking and indexing with boolean arrays

In [58]:
n = [6,7,8]
n[0:2]

[6, 7]

In [59]:
n[-1]

8

In [60]:
a = np.array([[6, 7, 8], [1, 2, 3], [9, 3, 2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [61]:
a[1, 2]

3

In [65]:
a[0:2, 2]

array([8, 3])

In [64]:
a[-1]

array([9, 3, 2])

In [66]:
a[-1, 0:2]

array([9, 3])

In [68]:
for row in a:
    print(row)


[6 7 8]
[1 2 3]
[9 3 2]


In [69]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [70]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [71]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [72]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [73]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [74]:
a =np.arange(30).reshape(2, 15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [75]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [76]:
result = np.hsplit(a,3)
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [77]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [78]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [80]:
result = np.vsplit(a,2)
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [83]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
b = a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [85]:
a[b] #gives no > 4

array([ 5,  6,  7,  8,  9, 10, 11])

In [87]:
a[b] = -1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [88]:
# iterate numpy array using nditer

In [89]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [91]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [93]:
for x in np.nditer(a, order='F'): #'C'
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [94]:
for x in np.nditer(a, order='F', flags=['external_loop']): 
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [96]:
for x in np.nditer(a, op_flags=['readwrite']): 
    x[...]=x*x

a

array([[    0,     1,    16,    81],
       [  256,   625,  1296,  2401],
       [ 4096,  6561, 10000, 14641]])

In [97]:
a

array([[    0,     1,    16,    81],
       [  256,   625,  1296,  2401],
       [ 4096,  6561, 10000, 14641]])

In [98]:
b = np.arange(3, 15, 4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [99]:
for x, y  in np.nditer([a,b]):
    print(x, y)

0 3
1 3
16 3
81 3
256 7
625 7
1296 7
2401 7
4096 11
6561 11
10000 11
14641 11
